default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DB_USERNAME") { "your_username" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "your_password" } %>
  host: localhost

development:
  <<: *default
  database: ruby_task_manager_development

test:
  <<: *default
  database: ruby_task_manager_test

production:
  <<: *default
  database: ruby_task_manager_production
  username: your_production_username
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
